#!/usr/bin/env python3
"""Render exact best-checkpoint operations for representative agent runs."""

from __future__ import annotations

import json
from pathlib import Path

import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch


ROOT = Path(__file__).resolve().parents[2]
PAPER = ROOT / "paper"
TRACES = PAPER / "data" / "traces"
OUT = PAPER / "figures"
ANALYSIS = PAPER / "data" / "analysis"

MODEL_SPECS = [
    ("Kimi K2.6", lambda run: run["agent_model"] == "kimi-k2.6", "#1F5FAE"),
    ("GPT-5.6 xhigh", lambda run: run["agent_variant"] == "gpt-5.6-sol [xhigh]", "#D97706"),
    ("GPT-5.5 high", lambda run: run["agent_variant"] == "gpt-5.5 [high]", "#2A7F62"),
    ("Claude Sonnet 4.6", lambda run: "sonnet" in run["agent_model"], "#7553A6"),
    ("Claude Opus 4.8", lambda run: "opus" in run["agent_model"], "#B64E73"),
    ("DeepSeek V4 Pro", lambda run: "deepseek" in run["agent_model"], "#677489"),
]


def select_runs() -> list[dict]:
    inventory = json.loads((TRACES / "agent_run_inventory_20260826_1922.json").read_text())["runs"]
    valid = [run for run in inventory if run.get("audit_verdict") == "valid"]
    selected = []
    for display_name, predicate, color in MODEL_SPECS:
        candidates = [run for run in valid if predicate(run)]
        if not candidates:
            raise RuntimeError(f"No valid run found for {display_name}")
        best = max(candidates, key=lambda run: run["best_observed_full_suite_score"])
        selected.append({**best, "display_name": display_name, "color": color})
    return selected


def format_scale(scale: float) -> str:
    return f"{scale:+.2e}".replace("e-0", "e-").replace("e+0", "e+")


def render() -> None:
    selected = select_runs()

    manifest = {
        "selection_rule": "highest-scoring audit-valid Qwen2.5-3B-Instruct run per agent model",
        "representation": (
            "Normalized replay form. Each line adds the deterministic full-model Gaussian "
            "direction generated by the recorded seed, scaled by the recorded coefficient."
        ),
        "runs": [
            {
                "model": run["display_name"],
                "run_id": run["run_id"],
                "best_score": run["best_observed_full_suite_score"] * 100,
                "one_direction_candidates": run["one_term_candidates"],
                "composed_candidates": run["multi_term_candidates"],
                "selected_terms": run["best_observed_terms"],
            }
            for run in selected
        ],
    }
    ANALYSIS.mkdir(parents=True, exist_ok=True)
    (ANALYSIS / "concrete_agent_operations.json").write_text(
        json.dumps(manifest, indent=2) + "\n"
    )

    mpl.rcParams.update(
        {
            "font.family": "sans-serif",
            "font.sans-serif": ["Arial", "Helvetica", "DejaVu Sans"],
            "font.size": 8.5,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
            "svg.fonttype": "none",
            "savefig.dpi": 320,
            "savefig.bbox": "tight",
            "savefig.pad_inches": 0.03,
        }
    )

    positive = "#2A7F62"
    negative = "#C97649"
    text = "#25324A"
    muted = "#778196"
    panel_fill = "#FBF9F5"
    panel_edge = "#D8D1C8"
    accent = "#B99372"

    display_order = [
        "Kimi K2.6",
        "Claude Sonnet 4.6",
        "GPT-5.6 xhigh",
        "DeepSeek V4 Pro",
        "GPT-5.5 high",
        "Claude Opus 4.8",
    ]
    by_name = {run["display_name"]: run for run in selected}
    ordered = [by_name[name] for name in display_order]

    fig = plt.figure(figsize=(7.15, 6.15))
    fig.patch.set_facecolor("white")
    grid = fig.add_gridspec(
        3,
        2,
        height_ratios=[0.82, 0.92, 1.45],
        left=0.012,
        right=0.988,
        top=0.992,
        bottom=0.008,
        wspace=0.06,
        hspace=0.08,
    )
    axes = [fig.add_subplot(grid[row, column]) for row in range(3) for column in range(2)]

    for panel_index, (ax, run) in enumerate(zip(axes, ordered)):
        terms = run["best_observed_terms"]
        ax.set_xlim(0, 1)
        ax.set_ylim(0, 1)
        ax.axis("off")

        panel = FancyBboxPatch(
            (0.01, 0.02),
            0.98,
            0.96,
            boxstyle="round,pad=0.006,rounding_size=0.018",
            facecolor=panel_fill,
            edgecolor=panel_edge,
            linewidth=0.7,
        )
        ax.add_patch(panel)
        ax.plot([0.025, 0.975], [0.835, 0.835], color=accent, lw=1.15)

        ax.text(
            0.045,
            0.91,
            chr(ord("a") + panel_index),
            ha="left",
            va="center",
            fontsize=8.5,
            color=muted,
        )
        ax.text(
            0.105,
            0.91,
            run["display_name"],
            ha="left",
            va="center",
            fontsize=9.0,
            color=text,
        )
        ax.text(
            0.955,
            0.91,
            f"k = {len(terms)}",
            ha="right",
            va="center",
            fontsize=7.5,
            color=muted,
        )

        line_count = len(terms) + 2
        max_step = 0.078 if panel_index >= 4 else 0.112
        step = min(max_step, 0.65 / max(line_count - 1, 1))
        y_positions = [0.75 - index * step for index in range(line_count)]

        def line_number(index: int, y_value: float) -> None:
            ax.text(
                0.055,
                y_value,
                f"{index:02d}",
                ha="left",
                va="center",
                fontsize=6.2,
                family="DejaVu Sans Mono",
                color="#A3A9B4",
            )

        line_number(1, y_positions[0])
        ax.text(
            0.12,
            y_positions[0],
            "state = copy(base)",
            ha="left",
            va="center",
            fontsize=6.9,
            family="DejaVu Sans Mono",
            color=text,
        )

        for term_index, (term, y_value) in enumerate(zip(terms, y_positions[1:-1]), start=2):
            coefficient = format_scale(term["scale"])
            coefficient_color = positive if term["scale"] >= 0 else negative
            line_number(term_index, y_value)
            ax.text(
                0.12,
                y_value,
                "state +=",
                ha="left",
                va="center",
                fontsize=6.9,
                family="DejaVu Sans Mono",
                color=text,
            )
            ax.text(
                0.34,
                y_value,
                coefficient,
                ha="left",
                va="center",
                fontsize=6.9,
                family="DejaVu Sans Mono",
                color=coefficient_color,
            )
            ax.text(
                0.52,
                y_value,
                f"* noise(seed={term['seed']})",
                ha="left",
                va="center",
                fontsize=6.9,
                family="DejaVu Sans Mono",
                color=text,
            )

        line_number(line_count, y_positions[-1])
        ax.text(
            0.12,
            y_positions[-1],
            "return state",
            ha="left",
            va="center",
            fontsize=6.9,
            family="DejaVu Sans Mono",
            color=accent,
        )

    OUT.mkdir(parents=True, exist_ok=True)
    for suffix in ("pdf", "png", "svg"):
        fig.savefig(OUT / f"fig6c-concrete-agent-operations.{suffix}")
    plt.close(fig)


if __name__ == "__main__":
    render()
