#!/usr/bin/env python3
"""Render exact best-checkpoint operations for representative agent runs."""

from __future__ import annotations

import json
from pathlib import Path

import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle


ROOT = Path(__file__).resolve().parents[2]
PAPER = ROOT / "paper"
TRACES = PAPER / "data" / "traces"
OUT = PAPER / "figures"
ANALYSIS = PAPER / "data" / "analysis"

MODEL_SPECS = [
    ("Kimi K2.6", lambda run: run["agent_model"] == "kimi-k2.6", "#1F5FAE"),
    ("GPT-5.6 xhigh", lambda run: run["agent_variant"] == "gpt-5.6-sol [xhigh]", "#D97706"),
    ("GPT-5.5 high", lambda run: run["agent_variant"] == "gpt-5.5 [high]", "#2A7F62"),
    ("Claude Sonnet 4.6", lambda run: "sonnet" in run["agent_model"], "#7553A6"),
    ("Claude Opus 4.8", lambda run: "opus" in run["agent_model"], "#B64E73"),
    ("DeepSeek V4 Pro", lambda run: "deepseek" in run["agent_model"], "#677489"),
]


def select_runs() -> list[dict]:
    inventory = json.loads((TRACES / "agent_run_inventory_20260826_1922.json").read_text())["runs"]
    valid = [run for run in inventory if run.get("audit_verdict") == "valid"]
    selected = []
    for display_name, predicate, color in MODEL_SPECS:
        candidates = [run for run in valid if predicate(run)]
        if not candidates:
            raise RuntimeError(f"No valid run found for {display_name}")
        best = max(candidates, key=lambda run: run["best_observed_full_suite_score"])
        selected.append({**best, "display_name": display_name, "color": color})
    return selected


def format_scale(scale: float) -> str:
    return f"{scale:+.2e}".replace("e-0", "e-").replace("e+0", "e+")


def operation_lines(terms: list[dict]) -> list[str]:
    lines = ["state = copy(base)"]
    for term in terms:
        lines.append(
            f"state += {format_scale(term['scale'])} * noise(seed={term['seed']})"
        )
    return lines


def render() -> None:
    selected = select_runs()

    manifest = {
        "selection_rule": "highest-scoring audit-valid Qwen2.5-3B-Instruct run per agent model",
        "representation": (
            "Normalized replay form. Each line adds the deterministic full-model Gaussian "
            "direction generated by the recorded seed, scaled by the recorded coefficient."
        ),
        "runs": [
            {
                "model": run["display_name"],
                "run_id": run["run_id"],
                "best_score": run["best_observed_full_suite_score"] * 100,
                "one_direction_candidates": run["one_term_candidates"],
                "composed_candidates": run["multi_term_candidates"],
                "selected_terms": run["best_observed_terms"],
            }
            for run in selected
        ],
    }
    ANALYSIS.mkdir(parents=True, exist_ok=True)
    (ANALYSIS / "concrete_agent_operations.json").write_text(
        json.dumps(manifest, indent=2) + "\n"
    )

    mpl.rcParams.update(
        {
            "font.family": "sans-serif",
            "font.sans-serif": ["Arial", "Helvetica", "DejaVu Sans"],
            "font.size": 8,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
            "svg.fonttype": "none",
            "savefig.dpi": 320,
            "savefig.bbox": "tight",
            "savefig.pad_inches": 0.03,
        }
    )

    fig, axes = plt.subplots(3, 2, figsize=(7.15, 6.75))
    fig.patch.set_facecolor("white")

    for ax, run in zip(axes.flat, selected):
        ax.set_xlim(0, 1)
        ax.set_ylim(0, 1)
        ax.axis("off")

        panel = Rectangle(
            (0.01, 0.015), 0.98, 0.97,
            facecolor="#FCFDFE", edgecolor="#CDD5DF", linewidth=0.65,
        )
        ax.add_patch(panel)
        ax.plot([0.025, 0.975], [0.935, 0.935], color=run["color"], lw=2.2)

        score = run["best_observed_full_suite_score"] * 100
        ax.text(
            0.045,
            0.875,
            run["display_name"],
            ha="left",
            va="center",
            fontsize=9.2,
            weight="semibold",
            color="#172033",
        )
        ax.text(
            0.955,
            0.875,
            f"{score:.2f}",
            ha="right",
            va="center",
            fontsize=9.2,
            weight="semibold",
            color=run["color"],
        )
        ax.text(
            0.045,
            0.795,
            f"evaluated {run['one_term_candidates']} probes + "
            f"{run['multi_term_candidates']} compositions",
            ha="left",
            va="center",
            fontsize=6.9,
            color="#596579",
        )

        lines = operation_lines(run["best_observed_terms"])
        y_top = 0.705
        y_bottom = 0.18
        step = min(0.092, (y_top - y_bottom) / max(len(lines) - 1, 1))
        font_size = 7.0 if len(lines) <= 5 else 6.35
        for index, line in enumerate(lines):
            ax.text(
                0.055,
                y_top - index * step,
                line,
                ha="left",
                va="center",
                fontsize=font_size,
                family="DejaVu Sans Mono",
                color="#25324A",
            )

        final_y = 0.075
        ax.text(
            0.055,
            final_y,
            f"evaluate(state)  ->  {score:.2f}",
            ha="left",
            va="center",
            fontsize=font_size,
            family="DejaVu Sans Mono",
            color=run["color"],
            weight="semibold",
        )

    fig.subplots_adjust(left=0.01, right=0.99, top=0.995, bottom=0.005, wspace=0.065, hspace=0.075)
    OUT.mkdir(parents=True, exist_ok=True)
    for suffix in ("pdf", "png", "svg"):
        fig.savefig(OUT / f"fig6c-concrete-agent-operations.{suffix}")
    plt.close(fig)


if __name__ == "__main__":
    render()
