#!/usr/bin/env python3
"""Render exact best-checkpoint operations for representative agent runs."""

from __future__ import annotations

import json
from pathlib import Path

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np


ROOT = Path(__file__).resolve().parents[2]
PAPER = ROOT / "paper"
TRACES = PAPER / "data" / "traces"
OUT = PAPER / "figures"
ANALYSIS = PAPER / "data" / "analysis"

MODEL_SPECS = [
    ("Kimi K2.6", lambda run: run["agent_model"] == "kimi-k2.6", "#1F5FAE"),
    ("GPT-5.6 xhigh", lambda run: run["agent_variant"] == "gpt-5.6-sol [xhigh]", "#D97706"),
    ("GPT-5.5 high", lambda run: run["agent_variant"] == "gpt-5.5 [high]", "#2A7F62"),
    ("Claude Sonnet 4.6", lambda run: "sonnet" in run["agent_model"], "#7553A6"),
    ("Claude Opus 4.8", lambda run: "opus" in run["agent_model"], "#B64E73"),
    ("DeepSeek V4 Pro", lambda run: "deepseek" in run["agent_model"], "#677489"),
]


def select_runs() -> list[dict]:
    inventory = json.loads((TRACES / "agent_run_inventory_20260826_1922.json").read_text())["runs"]
    valid = [run for run in inventory if run.get("audit_verdict") == "valid"]
    selected = []
    for display_name, predicate, color in MODEL_SPECS:
        candidates = [run for run in valid if predicate(run)]
        if not candidates:
            raise RuntimeError(f"No valid run found for {display_name}")
        best = max(candidates, key=lambda run: run["best_observed_full_suite_score"])
        selected.append({**best, "display_name": display_name, "color": color})
    return selected


def render() -> None:
    selected = select_runs()

    manifest = {
        "selection_rule": "highest-scoring audit-valid Qwen2.5-3B-Instruct run per agent model",
        "representation": (
            "Normalized replay form. Each line adds the deterministic full-model Gaussian "
            "direction generated by the recorded seed, scaled by the recorded coefficient."
        ),
        "runs": [
            {
                "model": run["display_name"],
                "run_id": run["run_id"],
                "best_score": run["best_observed_full_suite_score"] * 100,
                "one_direction_candidates": run["one_term_candidates"],
                "composed_candidates": run["multi_term_candidates"],
                "selected_terms": run["best_observed_terms"],
            }
            for run in selected
        ],
    }
    ANALYSIS.mkdir(parents=True, exist_ok=True)
    (ANALYSIS / "concrete_agent_operations.json").write_text(
        json.dumps(manifest, indent=2) + "\n"
    )

    mpl.rcParams.update(
        {
            "font.family": "sans-serif",
            "font.sans-serif": ["Arial", "Helvetica", "DejaVu Sans"],
            "font.size": 8.5,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
            "svg.fonttype": "none",
            "savefig.dpi": 320,
            "savefig.bbox": "tight",
            "savefig.pad_inches": 0.03,
        }
    )

    positive = "#2A7F62"
    negative = "#C97649"
    neutral = "#7A8494"
    grid = "#E5E9EF"
    text = "#202938"
    muted = "#667085"

    fig, axes = plt.subplots(3, 2, figsize=(7.15, 5.55), sharex=True)
    fig.patch.set_facecolor("white")

    for panel_index, (ax, run) in enumerate(zip(axes.flat, selected)):
        terms = run["best_observed_terms"]
        coefficients = np.array([term["scale"] * 1e3 for term in terms])
        positions = np.arange(len(terms))
        colors = [positive if value >= 0 else negative for value in coefficients]
        score = run["best_observed_full_suite_score"] * 100
        ax.axvline(0, color="#B8C0CC", lw=0.9, zorder=0)
        ax.hlines(positions, 0, coefficients, colors=colors, lw=2.2, zorder=2)
        ax.scatter(
            coefficients,
            positions,
            s=24,
            c=colors,
            edgecolors="white",
            linewidths=0.55,
            zorder=3,
        )
        for y_value, coefficient in zip(positions, coefficients):
            offset = 0.055 if coefficient >= 0 else -0.055
            ax.text(
                coefficient + offset,
                y_value,
                f"{coefficient:+.2f}",
                ha="left" if coefficient >= 0 else "right",
                va="center",
                fontsize=6.8,
                color=text,
            )

        ax.set_xlim(-1.55, 1.55)
        ax.set_ylim(len(terms) - 0.35, -0.75)
        ax.set_yticks(positions, [rf"$z_{{{index + 1}}}$" for index in positions])
        ax.set_xticks(np.arange(-1.5, 1.51, 0.5))
        ax.grid(axis="x", color=grid, linewidth=0.55, zorder=0)
        ax.tick_params(axis="y", length=0, pad=3, labelsize=7.2, colors=muted)
        ax.tick_params(axis="x", length=2.5, width=0.6, labelsize=7.0, colors=muted)
        for spine in ("top", "right", "left"):
            ax.spines[spine].set_visible(False)
        ax.spines["bottom"].set_color("#B8C0CC")
        ax.spines["bottom"].set_linewidth(0.65)

        ax.text(
            -0.11,
            1.10,
            chr(ord("a") + panel_index),
            transform=ax.transAxes,
            ha="left",
            va="top",
            fontsize=9,
            color=text,
            weight="semibold",
        )
        ax.text(
            0.0,
            1.10,
            run["display_name"],
            transform=ax.transAxes,
            ha="left",
            va="top",
            fontsize=8.8,
            color=text,
        )
        ax.text(
            1.0,
            1.10,
            f"score {score:.2f}",
            transform=ax.transAxes,
            ha="right",
            va="top",
            fontsize=8.2,
            color=text,
        )
        ax.text(
            0.0,
            1.01,
            f"k={len(terms)}  |  {run['one_term_candidates']} probes  |  "
            f"{run['multi_term_candidates']} compositions",
            transform=ax.transAxes,
            ha="left",
            va="top",
            fontsize=6.7,
            color=muted,
        )

    for ax in axes[-1, :]:
        ax.set_xlabel(r"Signed coefficient  $\alpha_i \times 10^{-3}$", fontsize=7.8, color=text)

    legend_handles = [
        mpl.lines.Line2D([0], [0], color=positive, marker="o", lw=2, markersize=4,
                         label="positive coefficient"),
        mpl.lines.Line2D([0], [0], color=negative, marker="o", lw=2, markersize=4,
                         label="negative coefficient"),
    ]
    fig.legend(
        handles=legend_handles,
        loc="upper center",
        bbox_to_anchor=(0.5, 0.995),
        ncol=2,
        frameon=False,
        fontsize=7.4,
        labelcolor=text,
        handlelength=1.8,
        columnspacing=1.6,
    )
    fig.subplots_adjust(left=0.075, right=0.985, top=0.91, bottom=0.075, wspace=0.20, hspace=0.48)
    OUT.mkdir(parents=True, exist_ok=True)
    for suffix in ("pdf", "png", "svg"):
        fig.savefig(OUT / f"fig6c-concrete-agent-operations.{suffix}")
    plt.close(fig)


if __name__ == "__main__":
    render()
