"use client";

import katex from "katex";
import { useState } from "react";
import type { ReactNode } from "react";
import InteractiveTrajectory from "./InteractiveTrajectory";
import WeightSpaceExplorer from "./WeightSpaceExplorer";
import RuntimeContract from "./RuntimeContract";
import AgentTraceExplorer from "./AgentTraceExplorer";

type Language = "zh" | "en";
type RunGroup = { name: string; harness: string; scores: number[] };

const tasks = [
  { name: "Countdown", zhType: "受约束算术", enType: "Constrained arithmetic", zhInput: "给定数字和目标值，用每个数字恰好一次构造四则运算表达式。", enInput: "Use every supplied number exactly once to construct an expression that reaches the target.", zhScore: "检查数字使用、表达式合法性与最终数值。", enScore: "Checks number use, expression validity, and the final value.", limit: "1,024" },
  { name: "GSM8K", zhType: "数学应用题", enType: "Math word problems", zhInput: "解决小学到初中难度的文字题，并给出最终数值。", enInput: "Solve grade-school word problems and return the final numeric answer.", zhScore: "抽取并规范化最终答案后精确匹配。", enScore: "Extracts and normalizes the final answer for exact matching.", limit: "1,024" },
  { name: "MATH-500", zhType: "竞赛数学", enType: "Competition math", zhInput: "求解代数、几何、数论和组合题。", enInput: "Solve problems in algebra, geometry, number theory, and combinatorics.", zhScore: "抽取数学答案并规范化后匹配。", enScore: "Extracts and normalizes the mathematical answer.", limit: "2,048" },
  { name: "OlympiadBench", zhType: "奥赛数学", enType: "Olympiad math", zhInput: "求解更高难度的英文开放式奥赛题。", enInput: "Solve harder English open-ended olympiad problems.", zhScore: "清理 LaTeX 并匹配最终答案。", enScore: "Cleans LaTeX and matches the final answer.", limit: "2,048" },
  { name: "MBPP", zhType: "程序生成", enType: "Code generation", zhInput: "根据函数需求和示例测试输出完整 Python 程序。", enInput: "Write a complete Python program from a function description and examples.", zhScore: "在隔离限时进程中运行全部测试。", enScore: "Runs all tests in an isolated, time-limited process.", limit: "2,048" },
  { name: "ROCStories", zhType: "叙事理解", enType: "Story ordering", zhInput: "恢复五个打乱句子的正确叙事顺序。", enInput: "Recover the correct order of five shuffled story sentences.", zhScore: "结合位置正确率与相邻句对正确率。", enScore: "Combines position accuracy and adjacent-pair accuracy.", limit: "64" },
  { name: "USPTO-50K", zhType: "化学分类", enType: "Reaction classification", zhInput: "根据反应 SMILES 判断 1–10 中的反应类别。", enInput: "Classify a reaction SMILES into one of ten reaction classes.", zhScore: "抽取类别编号并精确匹配。", enScore: "Extracts the class ID for exact matching.", limit: "64" },
];

const qwen25: RunGroup[] = [
  { name: "GPT-5.5 high", harness: "Codex", scores: [47.5621, 49.2307] },
  { name: "Kimi K2.6", harness: "OpenCode", scores: [47.5143, 47.5114, 49.25] },
  { name: "GPT-5.5 xhigh", harness: "Codex", scores: [48.1657, 47.6579, 45.8964, 48.125] },
  { name: "GPT-5.6 xhigh", harness: "Codex", scores: [46.8129, 48.6443, 46.5114, 47.3207, 46.6293] },
  { name: "GPT-5.6 high", harness: "Codex", scores: [46.9757, 47.2793, 46.2736] },
  { name: "GPT-5.4 Pro", harness: "OpenCode", scores: [46.8271] },
  { name: "GPT-5.6 medium", harness: "Codex", scores: [46.69] },
  { name: "DeepSeek V4 Pro", harness: "OpenCode", scores: [46.945, 45.6179, 47.1107] },
  { name: "Opus 4.8 high", harness: "Cursor", scores: [46.0964, 46.0393, 47.1329] },
  { name: "Sonnet 4.6 medium", harness: "Cursor", scores: [47.9164, 45.7171, 45.5929, 45.2393] },
  { name: "GLM-5.1", harness: "OpenCode", scores: [45.8857, 45.885, 46.19] },
  { name: "MiniMax M2.7", harness: "OpenCode", scores: [45.75] },
  { name: "Qwen3.7-Max", harness: "OpenCode", scores: [45.70] },
];

const qwen3: RunGroup[] = [
  { name: "MiniMax M2.7", harness: "OpenCode", scores: [48.9357, 49.0679] },
  { name: "Kimi K2.6", harness: "OpenCode", scores: [51.9436, 45.8807] },
  { name: "GPT-5.4 Pro", harness: "OpenCode", scores: [49.8921, 47.1979] },
  { name: "DeepSeek V4 Pro", harness: "OpenCode", scores: [46.2893, 50.2079] },
  { name: "GPT-5.6 xhigh", harness: "Codex", scores: [43.29, 53.19] },
  { name: "GLM-5.1", harness: "OpenCode", scores: [46.6714, 44.7421] },
  { name: "GPT-5.5 xhigh", harness: "Codex", scores: [47.4157, 42.9629] },
  { name: "Qwen3.7-Max", harness: "OpenCode", scores: [44.38] },
  { name: "GPT-5.5 Codex", harness: "Codex", scores: [42.91, 43.5993] },
];

function mean(values: number[]) { return values.reduce((sum, value) => sum + value, 0) / values.length; }

function Wordmark() {
  return <span className="wordmark" aria-label="PostTrainBench zero"><strong>PostTrainBench<sup>0</sup></strong><small>ZEROTH-ORDER POST-TRAINING</small></span>;
}

function Cite({ number }: { number: number }) {
  return <sup className="citation-ref"><a href={`#ref-${number}`} aria-label={`Reference ${number}`}>[{number}]</a></sup>;
}

function MathFormula({ latex, label, caption, compact = false }: { latex: string; label: string; caption: string; compact?: boolean }) {
  const html = katex.renderToString(latex, { displayMode: true, throwOnError: true, output: "htmlAndMathml" });
  return <figure className={compact ? "math-figure compact" : "math-figure"}>
    <div className="math-render" dangerouslySetInnerHTML={{ __html: html }} />
    <figcaption><b>{label}</b> {caption}</figcaption>
  </figure>;
}

function ResearchTable({ number, caption, children }: { number: number; caption: string; children: ReactNode }) {
  return <figure className="table-figure">
    <figcaption><b>Table {number}.</b> {caption}</figcaption>
    <div className="table-scroll">{children}</div>
  </figure>;
}

function ResearchFigure({ number, src, caption, interpretation, source, framework = false }: { number: number; src: string; caption: string; interpretation: string; source?: string; framework?: boolean }) {
  const [label, reading] = interpretation.split("｜");
  const imageSrc = src.startsWith("/") ? `${import.meta.env.BASE_URL}${src.slice(1)}` : src;
  return <figure className={framework ? "article-figure framework-figure" : "article-figure"}>
    <a href={imageSrc} target="_blank" rel="noreferrer" aria-label={`Open Figure ${number} at full resolution`}><img src={imageSrc} alt={caption} /></a>
    <figcaption><b>Figure {number}.</b> {caption}</figcaption>
    <p className="figure-reading"><b>{label}:</b> {reading}</p>
    {source ? <p className="figure-source">Python source: <code>{source}</code> · PNG shown; PDF retained for paper export.</p> : null}
  </figure>;
}

function RunsExplorer({ language }: { language: Language }) {
  const [model, setModel] = useState<"qwen25" | "qwen3">("qwen25");
  const rows = model === "qwen25" ? qwen25 : qwen3;
  const base = model === "qwen25" ? 44.0764 : 41.0821;
  const domain = model === "qwen25" ? [43.5, 50] : [40.5, 54];
  const place = (value: number) => `${((value - domain[0]) / (domain[1] - domain[0])) * 100}%`;
  return <div className="runs-explorer">
    <div className="explorer-head"><div><strong>{language === "zh" ? "逐次运行浏览" : "Run-by-run explorer"}</strong><span>{language === "zh" ? "每个蓝点是一轮完整运行，短黑线是该设置的平均值。" : "Each blue dot is one complete run; the black tick is the setting mean."}</span></div><div className="model-tabs" aria-label="Base model"><button className={model === "qwen25" ? "active" : ""} onClick={() => setModel("qwen25")}>Qwen2.5-3B</button><button className={model === "qwen3" ? "active" : ""} onClick={() => setModel("qwen3")}>Qwen3-4B</button></div></div>
    <div className="run-axis"><span>{domain[0]}</span><span>{((domain[0] + domain[1]) / 2).toFixed(1)}</span><span>{domain[1]}</span></div>
    <div className="run-rows">{rows.map((row) => { const average = mean(row.scores); return <div className="run-row" key={row.name}><div className="run-label"><strong>{row.name}</strong><small>{row.harness} · n={row.scores.length}</small></div><div className="run-track"><i className="base-reference" style={{ left: place(base) }} />{row.scores.map((score, index) => <button key={`${score}-${index}`} className="run-dot" style={{ left: place(score) }} title={`${row.name}: ${score.toFixed(2)}`} aria-label={`${row.name} score ${score.toFixed(2)}`} />)}<i className="mean-reference" style={{ left: place(average) }} /></div><b>{average.toFixed(2)}</b></div>; })}</div>
  </div>;
}

function RunSummaryTable({ rows, language }: { rows: RunGroup[]; language: Language }) {
  const ordered = [...rows].sort((a, b) => mean(b.scores) - mean(a.scores));
  return <table className="data-table run-summary"><thead><tr><th>Agent</th><th>Harness</th><th>n</th><th>{language === "zh" ? "平均分 ↑" : "Mean ↑"}</th><th>{language === "zh" ? "最小值–最大值" : "Min–max"}</th><th>{language === "zh" ? "最好分 ↑" : "Best ↑"}</th></tr></thead><tbody>{ordered.map((row) => <tr key={row.name}><td><b>{row.name}</b></td><td>{row.harness}</td><td>{row.scores.length}</td><td>{mean(row.scores).toFixed(2)}</td><td>{Math.min(...row.scores).toFixed(2)}–{Math.max(...row.scores).toFixed(2)}</td><td>{Math.max(...row.scores).toFixed(2)}</td></tr>)}</tbody></table>;
}

export default function Home() {
  const [language, setLanguage] = useState<Language>("en");
  const tx = (zh: string, en: string) => language === "zh" ? zh : en;
  return <main lang={language === "zh" ? "zh-CN" : "en"}>
    <header className="site-header"><a href="#top"><Wordmark /></a><nav><a href="#motivation">{tx("动机", "Motivation")}</a><a href="#benchmark">{tx("设置", "Setup")}</a><a href="#experiments">{tx("实验", "Experiments")}</a><a href="#conclusion">{tx("结论", "Conclusion")}</a></nav><div className="language-control" aria-label="Language"><button className={language === "zh" ? "active" : ""} onClick={() => setLanguage("zh")}>中文</button><button className={language === "en" ? "active" : ""} onClick={() => setLanguage("en")}>EN</button></div></header>
    <article className="research-article" id="top">
      <header className="article-header">
        <h1>PostTrainBench<sup>0</sup>: {tx("LLM Agent 能否在没有梯度的情况下完成模型后训练？", "Can LLM Agents Automate LLM Post-Training Without Gradients?")}</h1>
        <p className="article-meta">{tx("日期：2026 年 8 月", "Date: August 2026")} <span>·</span> {tx("预计阅读时间：24 分钟", "Estimated Reading Time: 24 min")} <span>·</span> {tx("作者：Yuqiao Tan", "Author: Yuqiao Tan")}</p>
        <p className="article-links"><a href="https://github.com/Trae1ounG/PostTrainBench0">Code &amp; data</a></p>
      </header>

      <aside className="table-of-contents"><details open><summary>{tx("目录", "Table of Contents")}</summary><ol>
        <li><a href="#motivation">{tx("从训练型 Agent 到无梯度模型改进", "From training agents to gradient-free improvement")}</a></li><li><a href="#benchmark">{tx("任务定义与实验设置", "Task definition and setup")}</a></li><li><a href="#system">{tx("系统、目录与完整指令", "System, workspace, and instruction")}</a></li><li><a href="#starting-points">{tx("RandOPT 与 ES", "RandOPT and ES")}</a></li><li><a href="#premise">{tx("前提实验：附近是否存在更好的权重", "Premise: do better nearby weights exist?")}</a></li><li><a href="#experiments">{tx("多模型 Agent 实验", "Multi-agent experiments")}</a></li><li><a href="#traces">{tx("搜索轨迹与行为分析", "Search trajectories and behavior")}</a></li><li><a href="#conclusion">{tx("发现与讨论", "Findings and discussion")}</a></li>
      </ol></details></aside>

      <section className="abstract-section"><h2>Abstract</h2><p>{tx("当反向传播不可用时，LLM Agent 还能否通过实验改进一个真实模型？我们提出 PostTrainBench⁰：一个面向 zeroth-order 后训练的长期 Agent 任务。每轮实验给 Agent 一个只读基础 checkpoint、可写工作区、只返回分数的评测器、八个推理 worker 和四小时预算；Agent 负责提出假设、编写搜索代码、构造并比较候选，最终产物是一个能够重新加载和重放的单一 checkpoint。前提实验表明这个搜索空间真实存在：在 Qwen3-4B 周围的 500 个受控随机候选中，62 个（12.4%）超过 41.08 的基础分，最好候选达到 46.03，同时七项任务偏好的扰动方向并不完全一致。我们进一步汇总了 Qwen2.5-3B-Instruct 与 Qwen3-4B-Base 上 51 次四小时 Agent 运行；每次运行都至少观察到一个高于基础分的完整七任务候选，最高分达到 53.19。与此同时，同一 Agent 设置的重复结果最多相差 9.90 分。由于固定 checkpoint 的重放是确定性的，这个跨度揭示了有限搜索本身的核心问题：策略质量、候选覆盖、系统吞吐和采样路径共同决定最终最好分。PostTrainBench⁰ 由此提供了一种成本较低、过程可观察、结果可重放的 AI-for-AI 实验形式，也把如何从随机搜索中可靠地测量 Agent 研究能力变成了一个具体问题。", "Can an LLM agent improve a real model through experimentation when backpropagation is unavailable? We introduce PostTrainBench⁰, a long-horizon agent task for zeroth-order post-training. Each run provides a read-only base checkpoint, a writable workspace, a score-only evaluator, eight inference workers, and four hours. The agent forms hypotheses, writes search code, constructs and compares candidates, and ultimately produces one checkpoint that can be reloaded and replayed. A controlled premise study confirms that the search space is real: among 500 random candidates around Qwen3-4B, 62 (12.4%) beat the 41.08 base score and the best reaches 46.03, while the seven tasks prefer different perturbation directions. We further consolidate 51 four-hour agent runs on Qwen2.5-3B-Instruct and Qwen3-4B-Base. Every run observes at least one complete seven-task candidate above its base, and the highest score reaches 53.19. At the same time, repeats of one agent setting differ by as much as 9.90 points. Because replaying a fixed checkpoint is deterministic, this spread exposes the central challenge of finite search: strategy quality, candidate coverage, system throughput, and the sampled path jointly shape the best score. PostTrainBench⁰ therefore offers a lower-cost, observable, and replayable form of AI-for-AI experimentation while turning reliable measurement of agent research ability under stochastic search into a concrete research question.")}</p></section>

      <section id="motivation"><h2>{tx("1. 为什么把梯度拿掉？", "1. Why remove gradients?")}</h2>
        <p>{tx("模型改进正在成为一类新的 Agent 任务。已有的 PostTrainBench 让 Agent 在一张 H100、十小时预算内自行准备数据、选择方法并训练基础模型；RSIBench-Data 则固定后训练栈，让 Agent 根据 checkpoint 反馈反复修改训练数据策略。二者都建立了同一个关键循环：Agent 提出研究决策，训练产生新模型，模型的评测结果再决定下一步。本文受这一方向启发，提出独立的无梯度设定 PostTrainBench⁰；上标 ⁰ 标记 zeroth-order，而非原论文的版本号。", "Model improvement is becoming an agent task in its own right. The existing PostTrainBench gives an agent one H100 for ten hours to prepare data, choose a method, and train a base model; RSIBench-Data fixes the post-training stack while the agent repeatedly revises training-data strategies from checkpoint feedback. Both instantiate the same core loop: the agent makes a research decision, training produces a new model, and evaluation determines the next decision. Inspired by this direction, we introduce PostTrainBench⁰ as an independent gradient-free setting; the superscript ⁰ denotes zeroth-order optimization, not a version of the original paper.")} <Cite number={1} /> <Cite number={5} /></p>
        <p>{tx("训练让这个循环既昂贵又复杂。每个假设都要经过数据处理、反向传播、优化器状态、checkpoint 保存、部署和评测；最终结果同时受研究决策与训练工程影响，也很难在同一预算下进行大量 Agent 对比和独立重复。PostTrainBench⁰ 把问题收缩到一个更基础的能力：拿走反向传播以后，Agent 能否仍然根据真实模型反馈，设计并执行一种有效的模型改进算法？", "Training makes this loop both expensive and complex. Every hypothesis must pass through data processing, backpropagation, optimizer state, checkpointing, serving, and evaluation. The outcome mixes research decisions with training engineering, while large agent comparisons and independent repeats remain difficult under a fixed budget. PostTrainBench⁰ narrows the problem to a more basic capability: after removing backpropagation, can an agent still use real model feedback to design and execute an effective model-improvement algorithm?")}</p>
        <p>{tx("这个问题并非凭空成立。Neural Thickets 表明，充分预训练模型附近可能密集存在具备不同任务能力的权重；简单参数扰动已经能够找到部分专家模型。PostTrainBench⁰ 把这项观察变成一个长期研究任务：Agent 必须决定搜索哪些参数、使用什么方向和尺度、如何分配七项任务的评测预算，以及如何把多次反馈收敛为一个通用 checkpoint。", "The question has an empirical basis. Neural Thickets suggests that the neighborhood of a well-pretrained model may contain many weights with different task capabilities, and that simple parameter perturbations can already recover some specialists. PostTrainBench⁰ turns this observation into a long-horizon research task: the agent must decide which parameters to search, which directions and scales to use, how to allocate evaluation across seven tasks, and how to consolidate feedback into one general checkpoint.")} <Cite number={2} /></p>
        <MathFormula
          latex={String.raw`J(\theta)=\frac{100}{|\mathcal{T}|}\sum_{t\in\mathcal{T}}s_t(\theta),\qquad |\mathcal{T}|=7,\quad s_t(\theta)\in[0,1]\tag{1}`}
          label={tx("公式 (1).", "Equation (1).")}
          caption={tx("联合分数的定义。θ 是待评测的单一 checkpoint，T 是七个任务的集合，s_t(θ) 是任务 t 在固定 200 条样本上的 0–1 分数。J(θ) 是七项等权平均后的 0–100 分数。评测器返回各任务分数与 J(θ)，但不返回任何对参数的导数。", "Definition of the joint score. Here, θ is one candidate checkpoint, T is the seven-task suite, and s_t(θ) is the 0–1 score for task t on its fixed 200 examples. J(θ) is their equal-weight mean on a 0–100 scale. The evaluator returns per-task scores and J(θ), but no derivative with respect to model parameters.")}
        />
        <p>{tx("上标 ⁰ 表示 zeroth-order：评测器只返回候选模型的函数值，不提供任何参数导数。候选加载和前向推理依然消耗 GPU，因此这不是“零计算”；它去掉的是显式训练步骤。这个设置与 RSI 的研究目标相关，但不是严格的递归自我改进：研究 Agent 和目标模型是两个系统，改进后的模型也不会在当前实验里接替 Agent。我们测量的是一项边界更清楚的 AI-for-AI 能力——一个通用 Agent 能否像研究员一样，通过可验证实验改进另一个模型。", "The superscript ⁰ denotes zeroth-order optimization: the evaluator returns function values for candidate models but no parameter derivatives. Candidate loading and forward inference still consume GPUs, so this is not zero compute; it removes the explicit training step. The setting relates to the research agenda around recursive self-improvement, but it is not strict RSI: the research agent and target model are separate systems, and the improved model does not replace the agent in the current experiment. We measure a more bounded AI-for-AI capability—whether a general agent can improve another model through verifiable experimentation.")}</p>
        <blockquote>{tx("核心难点不是找到任意一个涨分点，而是在多个任务存在冲突时，找到一个单一、可重放、平均表现更好的 checkpoint。", "The goal is not merely to find any improvement. It is to find one replayable checkpoint with a better average when the tasks prefer different directions.")}</blockquote>
        <h3>{tx("我们希望回答三个问题", "Three questions guide the study")}</h3><ol className="prose-list"><li>{tx("基础模型附近是否真的存在可搜索的改进？", "Do useful improvements actually exist near the base model?")}</li><li>{tx("Agent 能否把多任务分数转化为有效的搜索决策？", "Can an agent turn multi-task scores into effective search decisions?")}</li><li>{tx("最终分数反映 Agent 能力，还是主要反映随机路径？", "Does the endpoint reflect agent capability or mostly a lucky search path?")}</li></ol>
      </section>

      <section id="benchmark"><h2>{tx("2. Benchmark 的任务定义与实验设置", "2. Benchmark definition and experimental setup")}</h2>
        <p>{tx("一次正式运行优化同一个 checkpoint 在七项任务上的等权平均。七项任务故意覆盖不同输出形式：数学答案、可执行代码、句子顺序和化学类别。它们不是为了穷尽模型能力，而是为了让一个权重修改同时面对多个方向的反馈。", "A formal run optimizes the equal-weight mean of one checkpoint over seven tasks. The tasks deliberately cover different outputs—mathematical answers, executable code, sentence order, and reaction classes. They are not intended to exhaust model capability; they create multi-directional feedback for a single weight edit.")}</p>
        <h3>{tx("评测任务", "Evaluation tasks")}</h3>
        <ResearchTable number={1} caption={tx("每次完整 checkpoint 评测使用的七任务集。n 表示每个任务固定评测的样本数；“输出上限”是每条样本允许生成的最多 token 数。一个候选共执行 7 × 200 = 1,400 条推理。联合分数是七个任务分数的等权平均，不按样本数再加权。", "The seven-task suite used for every complete checkpoint evaluation. n is the fixed number of examples per task; the output limit is the maximum number of generated tokens per example. One candidate therefore requires 7 × 200 = 1,400 inferences. The joint score is the equal mean of the seven task scores, not an additional sample-weighted average.")}>
          <table className="data-table task-detail-table"><thead><tr><th>{tx("任务", "Task")}</th><th>{tx("类型", "Type")}</th><th>{tx("输入与目标", "Input and target")}</th><th>{tx("评分", "Scoring")}</th><th>n</th><th>{tx("输出上限", "Token limit")}</th></tr></thead><tbody>{tasks.map((task) => <tr key={task.name}><td><b>{task.name}</b></td><td>{language === "zh" ? task.zhType : task.enType}</td><td>{language === "zh" ? task.zhInput : task.enInput}</td><td>{language === "zh" ? task.zhScore : task.enScore}</td><td>200</td><td>{task.limit}</td></tr>)}</tbody></table>
        </ResearchTable>
        <h3>{tx("固定条件", "Fixed conditions")}</h3>
        <ResearchTable number={2} caption={tx("四小时主实验的共同执行合约。四小时从 Agent 启动时开始计时，包括 Agent 思考、API 等待、代码执行与模型评测。八张 GPU 只运行独立推理 worker 来提高吞吐；每个分数仍属于一个单一 checkpoint，不使用 ensemble。", "The execution contract shared by the four-hour main experiments. The clock starts with the agent and includes deliberation, API waiting, code execution, and model evaluation. Eight GPUs host independent inference workers only to increase throughput; every reported score still belongs to one checkpoint, with no ensemble.")}>
          <table className="data-table setting-table"><tbody><tr><th>{tx("目标模型", "Target models")}</th><td>Qwen2.5-3B-Instruct · Qwen3-4B-Base, BF16</td></tr><tr><th>Agent harness</th><td>Codex CLI · OpenCode CLI · Cursor Agent</td></tr><tr><th>{tx("时间预算", "Wall-clock budget")}</th><td>4 hours per independent run</td></tr><tr><th>GPU</th><td>8 × H20-96GB · 8 resident inference workers</td></tr><tr><th>{tx("解码", "Decoding")}</th><td>temperature 0 · generation seed 42 · task-specific token limits</td></tr><tr><th>{tx("搜索自由度", "Search freedom")}</th><td>{tx("任意无梯度方法；可串行或并行；可先评测任务子集", "Any gradient-free method; serial or parallel; task subsets allowed")}</td></tr><tr><th>{tx("最终产物", "Final artifact")}</th><td>{tx("一个能够全新加载并重放七项任务的 checkpoint", "One checkpoint that reloads and replays all seven tasks")}</td></tr></tbody></table>
        </ResearchTable>
        <div className="section-finding"><b>{tx("这里需要记住的边界", "The boundary to keep in mind")}</b><p>{tx("所有 Agent 面对同一个联合目标、推理设置和 GPU 数量。八张卡只提高候选评测吞吐，不构成 ensemble；每个分数始终对应一个独立模型。", "Every agent faces the same joint objective, decoding setup, and GPU count. Eight GPUs increase candidate throughput but never form an ensemble; every score belongs to one independent model.")}</p></div>
      </section>

      <section id="system"><h2>{tx("3. 一次四小时实验到底如何运行？", "3. How does a four-hour episode actually run?")}</h2>
        <p>{tx("Agent 控制研究过程，可信系统控制评测过程。这个分界是 benchmark 能够被校验的关键：Agent 可以自由写代码和创建候选，但不能查看题目答案、修改计分方式或让最终模型依赖外部服务。", "The agent controls the research process while the trusted system controls evaluation. This boundary makes the benchmark auditable: the agent may write code and create candidates, but it cannot inspect answers, alter scoring, or make the final model depend on an external service.")}</p>
        <p>{tx("本文中的 harness 不是 Agent 模型本身，而是包围 Agent 的执行边界：它决定 Agent 看得到什么、能写什么、如何计时，以及什么结果能被验收。这种将模型能力与执行环境分开的观点也是 harness engineering 讨论的核心。", "Here, the harness is not the agent model itself. It is the execution boundary around the agent: what the agent can see and write, how time is measured, and which outputs can be accepted. Separating model capability from this surrounding execution system is also central to discussions of harness engineering.")} <Cite number={4} /></p>
        <ResearchFigure number={1} framework src="/figures/posttrainbench-system.png" caption={tx("PostTrainBench⁰ 的系统设计。Agent 获得只读基础 checkpoint、只返回分数的评测接口、四小时时间预算和八个推理 worker；它在可写工作区中生成候选。每个候选先经过合规检查，再由可信评测器完成七任务评测。到达时限后，系统保留 Agent 找到的最佳单一 checkpoint。", "System design of PostTrainBench⁰. The agent receives a read-only base checkpoint, a score-only evaluation API, a four-hour wall-clock budget, and eight inference workers, then produces candidates in a writable workspace. Each candidate passes compliance checks before trusted seven-task evaluation. At timeout, the system retains the single best checkpoint found by the agent.")} interpretation={tx("如何阅读｜从左到右是一次候选评测；上方分支处理违规结果；底部橙色回路把分数返回 Agent，允许它在四小时内继续搜索。小图标分别标记模型、接口、时间、GPU、工作区、checkpoint、审计、任务集和联合分数。", "How to read it｜Left to right shows one candidate evaluation; the upper branch handles violations; the orange loop returns scores so the agent can continue searching within four hours. The compact icons identify the model, API, clock, GPUs, workspace, checkpoint, audit, task suite, and joint score.")} />
        <h3>{tx("配置一次运行：权重路径、运行根目录与 Agent CLI", "Configuring one run: model weights, run root, and Agent CLI")}</h3>
        <p>{tx("操作员不会把整台机器交给 Agent。启动前，配置文件明确给出基础权重目录、隐藏评测数据目录、所有运行的统一根目录，以及所选 harness 的 CLI。运行时系统创建一个从未使用过的 run_id，并把其中的 workspace 映射为 Agent 的 /home/agent；基础 checkpoint 单独映射为只读 /models/base。", "The operator does not hand the whole machine to the Agent. Before launch, one config names the base-weight directory, hidden evaluation-data directory, common root for append-only runs, and the CLI for the selected harness. The runtime creates a never-before-used run_id, maps its workspace to /home/agent, and mounts the base checkpoint separately as read-only /models/base.")}</p>
        <RuntimeContract language={language} />
        <p>{tx("每次 evaluate 都留下永久 attempt 记录。最终验收不是复用搜索过程中已经驻留的模型，而是在全新推理实例中重新加载候选，并完整重放七项任务。trace 审计同时检查 backward、autograd、模型替换、评测器访问和 ensemble。", "Every evaluation creates a permanent attempt record. Final acceptance does not reuse a model left resident during search: it reloads the candidate in a fresh inference instance and replays the full seven-task suite. Trace auditing checks for backward passes, autograd, model substitution, evaluator access, and ensembles.")}</p>
        <div className="section-finding"><b>{tx("为什么要把两边分开", "Why the boundary matters")}</b><p>{tx("Agent 的自由度位于搜索算法和实验安排，而不是评测器。最后分数来自可信系统对单一 checkpoint 的重放，因此可以把“模型真的变好”与“Agent 声称变好”分开。", "Agent freedom lies in the search algorithm and experiment schedule, not in the evaluator. The final score comes from trusted replay of one checkpoint, separating an actual model improvement from an agent's claim of improvement.")}</p></div>
      </section>

      <section id="starting-points"><h2>{tx("4. 两个起始方法：RandOPT 与 ES", "4. Two starting methods: RandOPT and ES")}</h2>
        <p>{tx("完成度最高的历史实验给 Agent 两段很短的起始代码。它们负责正确加载权重、生成候选和调用并行评测，Agent 可以直接使用、修改或替换。它们不是最终答案，而是让 Agent 把时间花在搜索决策而不是重复搭建底层工程。", "The most complete historical protocol provides two short starting implementations. They handle correct weight loading, candidate construction, and parallel evaluation; the agent may use, modify, or replace them. They are not prescribed solutions—they keep the episode focused on search decisions rather than rebuilding infrastructure.")}</p>
        <div className="method-pair"><div><h3>RandOPT</h3><p>{tx("Neural Thickets 将 RandOPT 定义为：从预训练权重附近独立采样 N 个扰动模型，保留分数最高的 K 个候选，并在原文中用多数投票集成。我们的 benchmark 必须交付一个 checkpoint，因此基线采用 K=1：只保留联合分数最高的候选。", "Neural Thickets defines RandOPT by sampling N independently perturbed models around pretrained weights, retaining the top K, and ensembling their predictions by majority vote. Our benchmark must deliver one checkpoint, so the baseline uses K=1 and keeps only the candidate with the highest joint score.")} <Cite number={2} /></p><MathFormula compact latex={String.raw`\epsilon_i\sim\mathcal{N}(0,I),\qquad \theta_i=\theta_0+\sigma\epsilon_i,\qquad i^\star=\arg\max_{1\le i\le N}J(\theta_i),\quad \widehat\theta=\theta_{i^\star}\tag{2}`} label={tx("公式 (2).", "Equation (2).")} caption={tx("单 checkpoint RandOPT。θ₀ 是基础权重，ε_i 是独立高斯扰动方向，σ 控制扰动幅度，N 是候选数。最终权重是联合分数 J 最高的单一候选。", "Single-checkpoint RandOPT. Here, θ₀ is the base weight vector, ε_i is an independent Gaussian direction, σ controls perturbation magnitude, and N is the number of candidates. The output is the single candidate with the highest joint score J.")} /></div><div><h3>Evolution Strategy</h3><p>{tx("我们的 ES 起始实现与 Neural Thickets 使用的 ES 基线一致：对高斯扰动后的候选进行无梯度评测，再根据候选分数加权这些扰动，更新下一轮搜索中心。实现中使用正反成对扰动，以减少方向估计的方差。该基线直接来自 Evolution Strategies at Scale。", "Our ES starting point follows the ES baseline used by Neural Thickets: evaluate Gaussian-perturbed candidates without gradients, weight those perturbations by candidate fitness, and update the next search center. The implementation uses antithetic perturbation pairs to reduce estimator variance. The baseline is taken directly from Evolution Strategies at Scale.")} <Cite number={2} /> <Cite number={3} /></p><MathFormula compact latex={String.raw`\widehat g_k=\frac{1}{2N\sigma}\sum_{i=1}^{N}\left[J(\theta_k+\sigma\epsilon_i)-J(\theta_k-\sigma\epsilon_i)\right]\epsilon_i,\qquad \theta_{k+1}=\theta_k+\alpha\widehat g_k\tag{3}`} label={tx("公式 (3).", "Equation (3).")} caption={tx("成对扰动的 ES 中心更新。θ_k 是第 k 轮搜索中心，N 是扰动方向数，σ 是评估扰动幅度，α 是中心更新步长。g-hat 是由函数值差构造的方向估计；它不需要 autograd 或反向传播。", "Antithetic ES center update. Here, θ_k is the search center at iteration k, N is the number of sampled directions, σ is the evaluation scale, and α is the center step size. The direction estimate g-hat is constructed from score differences and requires neither autograd nor backpropagation.")} /></div></div>
        <p>{tx("在 Qwen2.5-3B 上，三组 360 次 RandOPT 的最好分数为 45.81–46.41。保守步长的 ES 曾达到 54.68，而原始 ES 设置只有 44.97。这不是 ES 已经解决任务的证据；相反，它说明中心更新可能有效，但结果对步长和方向高度敏感。", "On Qwen2.5-3B, three 360-evaluation RandOPT runs reached best scores of 45.81–46.41. A conservative-step ES run reached 54.68, while the original ES setting reached only 44.97. This does not mean ES solves the task; it shows that center updates can matter while remaining highly sensitive to step size and directions.")}</p>
        <div className="section-finding"><b>{tx("我们真正想观察的行为", "The behavior we want to observe")}</b><p>{tx("RandOPT 和 ES 只是起点。Agent 的价值应体现在能否根据反馈选择搜索机制、控制步长、复用历史最好点，并在固定时间内减少无效评测；如果最终差异只来自谁随机抽中了一个好方向，这个 benchmark 就没有完成它的目标。", "RandOPT and ES are starting points. Agent value should appear in how it selects a search mechanism from feedback, controls step size, reuses incumbents, and avoids wasted evaluations. If final differences only reflect who happened to sample a good direction, the benchmark has not achieved its goal.")}</p></div>
      </section>

      <section id="premise"><h2>{tx("5. 前提实验：这个搜索问题真的存在吗？", "5. Premise check: is there a real search problem?")}</h2>
        <p>{tx("在比较 Agent 之前，我们先验证两个前提：基础模型附近确实存在更好的权重；同时，随便抽一个候选并不会稳定提高联合分数。否则，Agent 实验要么无解，要么只是在计数随机试验。", "Before comparing agents, we test two premises: better weights must exist near the base, yet a random candidate should not reliably improve the joint score. Otherwise the agent task would be either impossible or merely a count of random trials.")}</p>
        <ResearchFigure number={2} src="/figures/premise-check.png?v=2" caption={tx("Qwen2.5-3B 与 Qwen2.5-7B 上的 192 个受控扰动。灰点是基础模型，蓝点是同一个候选能达到的最好均分，橙色星号是允许每项任务分别挑选候选时的 oracle。", "A controlled 192-candidate perturbation study on Qwen2.5-3B and Qwen2.5-7B. Gray marks the base, blue the best single joint checkpoint, and orange the oracle obtained by choosing a different checkpoint per task.")} source="scripts/render_premise_figure.py" interpretation={tx("发现｜两个目标模型附近都存在更好的单一 checkpoint，但任务分别取最优的 oracle 仍高出约 4.5 分。这说明局部改进可行，而把不同能力装进同一个 checkpoint 仍然困难。", "Finding｜Both target models have a better single checkpoint nearby, yet the task-wise oracle remains about 4.5 points higher. Local improvement is feasible; combining task gains in one checkpoint remains hard.")} />
        <h3>{tx("更大规模的精确恢复检查", "A larger exact-reset check")}</h3><p>{tx("我们随后在 Qwen3-4B 上评测 500 个独立扰动。每个候选都从保存的基础 tensor 精确重建，避免 BF16 下用“加噪声再减噪声”产生累积漂移。结果中 62/500 个候选超过 41.08 的基础均分；最好候选达到 46.03，提高五项任务、降低两项。没有候选同时提高七项任务，而逐任务挑选的 oracle 达到 56.62。", "We then evaluated 500 independent perturbations on Qwen3-4B. Every candidate was rebuilt from stored base tensors, avoiding BF16 drift from add-then-subtract restoration. Sixty-two of 500 candidates beat the 41.08 base mean; the best reached 46.03, improving five tasks and hurting two. No candidate improved all seven tasks, while the task-wise oracle reached 56.62.")}</p>
        <div className="table-scroll"><table className="data-table premise-summary"><thead><tr><th>{tx("指标", "Measure")}</th><th>{tx("结果", "Result")}</th></tr></thead><tbody><tr><td>{tx("随机候选超过基础均分", "Candidates above base")}</td><td>12.4%</td></tr><tr><td>{tx("最好单一 checkpoint", "Best single checkpoint")}</td><td>46.03</td></tr><tr><td>{tx("逐任务 oracle", "Task-wise oracle")}</td><td>56.62</td></tr><tr><td>{tx("同时提高全部七项", "Improved all seven tasks")}</td><td>0 / 500</td></tr></tbody></table></div>
        <ResearchFigure number={3} src="/figures/weight-neighborhood-and-task-directions.png" caption={tx("Qwen2.5-7B 的 192 个候选在同一权重投影中的位置。左图按七任务均分着色；右图从基础模型指向每项任务的最好候选。", "The same 192 Qwen2.5-7B candidates in one weight projection. The left panel colors candidates by the seven-task mean; the right points from the base toward each task specialist.")} source="scripts/render_blog_extended_figures.py" interpretation={tx("发现｜任务最佳点分散在不同方向。二维坐标由实际 BF16 权重差的草图投影得到，且不使用分数；它可以描述相对方向，但不能证明高维权重空间存在稳定簇。", "Finding｜Task optima spread across different directions. Coordinates come from a score-independent projection of sketches of actual BF16 weight differences. They describe relative directions but do not prove stable clustering in the full space.")} />
        <ResearchFigure number={4} src="/figures/task-alignment-and-scale-sensitivity.png" caption={tx("同一批候选上的任务排序相关性与扰动幅度敏感性。左图比较不同任务如何排列候选；右图统计不同幅度下超过任务基础分的比例。", "Task-rank correlation and perturbation-scale sensitivity on the same candidates. The left compares how tasks rank candidates; the right counts task improvements at each scale.")} source="scripts/render_blog_extended_figures.py" interpretation={tx("发现｜任务关系是混合的：少数任务排序相近，许多关系较弱。更大的扰动也不是普遍更好；安全步长取决于任务。因此 Agent 同时需要学习方向和尺度。", "Finding｜Task structure is mixed: a few rankings align while many relationships are weak. Larger perturbations are not uniformly better; safe step size depends on the task. An agent must learn both direction and scale.")} />
        <div className="section-finding"><b>{tx("这个前提实验改变了什么", "What the premise study changes")}</b><p>{tx("它说明附近确实有更好的 checkpoint，因此任务不是空的；但高分方向稀疏、任务之间存在交换，也意味着有限采样会强烈影响一次运行能看到什么。长时搜索有真实空间，同时也天然容易把运气误当成能力。", "It shows that better nearby checkpoints exist, so the task is not empty. But sparse high-score directions and task trade-offs also mean that finite sampling strongly controls what any run gets to observe. The task has a real search space, while naturally risking confusion between luck and capability.")}</p></div>
      </section>

      <section id="experiments"><h2>{tx("6. 多模型 Agent 实验：最终分数告诉了我们什么？", "6. Multi-agent experiments: what do endpoint scores tell us?")}</h2>
        <p>{tx("我们重新整理了四小时、七任务协议下的全部完整运行。只要一次运行产生完整七任务分数，就计为一个观测；在任何有效评测之前发生的环境启动失败不计。这样既不会因为最后的提交命令超时而丢掉已经完成的实验，也不会把没有模型结果的系统故障混入排名。", "We consolidate all complete runs under the four-hour, seven-task protocol. A run counts once it produces a complete seven-task score; environment failures before any valid evaluation are excluded. This retains completed model experiments when a final command times out, while keeping infrastructure-only failures out of the comparison.")}</p>
        <h3>{tx("先把“随机性”说清楚", "First, what exactly is random?")}</h3>
        <p>{tx("同一个 checkpoint 被重新加载后，评测使用固定的 200 条样本、贪心解码和固定生成 seed；在实现正确时，得到的分数应当一致。因此 Figure 5 中的大幅波动不能简单归因于评测器抖动。真正变化的是搜索过程：Agent 每轮抽到的权重方向不同，选择的尺度和组合不同，并且后续决策会依赖前几轮是否碰巧出现了好点。", "A checkpoint is replayed on the same 200 examples with greedy decoding and a fixed generation seed, so a correct implementation should reproduce its score. The large spread in Figure 5 is therefore not ordinary evaluator noise. What changes is the search process: agents encounter different weight directions, choose different scales and combinations, and make later decisions based on whether early probes happened to find promising points.")}</p>
        <ResearchTable number={3} caption={tx("当前协议中的五个主要随机性来源。前四项改变一次运行探索到的候选集合；最后一项会让开发分数逐渐参与搜索策略本身。", "Five main sources of variation in the current protocol. The first four change the candidate set explored in a run; the last allows development scores to become part of the search strategy itself.")}><table className="data-table"><thead><tr><th>{tx("来源", "Source")}</th><th>{tx("一次运行中发生什么", "What changes within a run")}</th><th>{tx("为什么影响比较", "Why it affects comparison")}</th></tr></thead><tbody>
          <tr><td><b>{tx("方向采样", "Direction sampling")}</b></td><td>{tx("随机 seed 决定具体访问哪些高维权重方向。", "Random seeds determine which high-dimensional weight directions are visited.")}</td><td>{tx("好方向较稀疏时，少量幸运样本就可能决定最高分。", "When useful directions are sparse, a few lucky samples can determine the maximum.")}</td></tr>
          <tr><td><b>{tx("尺度与组合", "Scale and composition")}</b></td><td>{tx("Agent 选择扰动幅度，并决定是否在已有候选上叠加方向。", "The agent chooses perturbation magnitudes and whether to compose directions around an incumbent.")}</td><td>{tx("同一方向在不同尺度下可能从有益变成破坏性。", "The same direction may change from useful to destructive at another scale.")}</td></tr>
          <tr><td><b>{tx("路径依赖", "Path dependence")}</b></td><td>{tx("早期高分会成为中心，影响后续所有局部搜索。", "An early high score may become the center for all subsequent local search.")}</td><td>{tx("一次偶然发现会被后续优化放大，重复运行容易分叉。", "One chance discovery can be amplified, causing repeat runs to diverge.")}</td></tr>
          <tr><td><b>{tx("候选数量", "Candidate count")}</b></td><td>{tx("API 速度、代码效率和任务子集策略决定四小时内能完成多少次评测。", "API speed, code efficiency, and task-subset policy determine how many evaluations fit into four hours.")}</td><td>{tx("即使策略完全相同，样本更多也会提高观察到更大极值的概率。", "Even with the same policy, more samples increase the expected observed maximum.")}</td></tr>
          <tr><td><b>{tx("开发集适应", "Development-set adaptation")}</b></td><td>{tx("Agent 可以反复看到同一批任务的分数，并据此选择候选。", "The agent repeatedly observes scores on the same task set and selects candidates accordingly.")}</td><td>{tx("最终高分可能包含对这 200 条样本的适应，而不代表不可见数据上的泛化。", "The final score may include adaptation to these 200 examples rather than hidden-data generalization.")}</td></tr>
        </tbody></table></ResearchTable>
        <p>{tx("这里最关键的统计事实是：我们记录的是一次运行中观察到的最好值。最好值是一个极值统计量，它同时奖励搜索质量和搜索数量。如果两个 Agent 分别完成 20 次和 200 次完整评测，即使它们从同一个分布随机抽样，后者也更可能得到更高的最好分。因此，当前结果适合分析行为和提出问题，不适合直接宣称模型能力排序。", "The key statistical fact is that we record the best value observed during a run. A maximum rewards both search quality and search quantity. If two agents complete 20 and 200 full evaluations, the latter is more likely to report a higher best score even when both sample from the same distribution. The present results are therefore useful for behavioral analysis and benchmark design, but not for claiming a clean capability ranking.")}</p>
        <ResearchFigure number={5} src="/figures/historical-agent-runs.png" caption={tx("Qwen2.5-3B-Instruct 与 Qwen3-4B-Base 上的全部历史完整运行。蓝点是一轮运行中的最好完整分数，黑线是同一设置的平均，虚线是基础模型。", "All complete historical runs on Qwen2.5-3B-Instruct and Qwen3-4B-Base. Blue dots are the best complete scores in individual runs, black ticks are setting means, and dashed lines are base checkpoints.")} source="scripts/render_blog_figures.py" interpretation={tx("发现｜Qwen2.5-3B 上的结果较集中，但不同 Agent 的均值差距不大；Qwen3-4B 上单个设置的重复跨度可接近 10 分。最高分能够展示搜索上限，却不足以单独构成稳定的 Agent 排名。", "Finding｜Results are tighter on Qwen2.5-3B, but mean gaps between agents are small. On Qwen3-4B, repeats of one setting can span nearly ten points. A best score reveals search potential but is insufficient for a stable agent ranking.")} />
        <h3>Qwen2.5-3B-Instruct · 34 {tx("次完整运行", "complete runs")}</h3><p>{tx("基础模型为 44.08。按已完成运行的平均分，GPT-5.5 high 与 Kimi K2.6 位于最前，但二者均只有 2–3 次重复；多数设置的平均分集中在 45.7–48.4。这里能看到稳定提升，却看不到与通用 Agent 排名一致的单调排序。", "The base score is 44.08. GPT-5.5 high and Kimi K2.6 lead by the mean of completed runs, but each has only two or three repeats; most settings fall between 45.7 and 48.4. Improvements are consistent, but the ordering is not monotonic with general agent rankings.")}</p><ResearchTable number={4} caption={tx("Qwen2.5-3B-Instruct 上的 34 次独立四小时运行，按 Agent 和 harness 分组汇总。n 是完整运行数；“平均分”是该组所有运行的算术平均；“最小值–最大值”显示重复波动；“最好分”是任一单次运行达到的最高值。基础 checkpoint 的七任务均分为 44.08。", "All 34 independent four-hour runs on Qwen2.5-3B-Instruct, grouped by agent and harness. n is the number of complete runs; Mean is the arithmetic mean across those runs; Min–max exposes repeat variability; Best is the highest score reached in any one run. The base checkpoint scores 44.08.")}><RunSummaryTable rows={qwen25} language={language} /></ResearchTable>
        <h3>Qwen3-4B-Base · 17 {tx("次完整运行", "complete runs")}</h3><p>{tx("基础模型为 41.08。MiniMax M2.7 的两次运行都接近 49；GPT-5.6 xhigh 同时得到 53.19 和 43.29，跨越 9.90 分；Kimi K2.6、DeepSeek V4 Pro 和 GPT-5.4 Pro 也有明显的重复波动。这说明目标模型本身会改变搜索地形和可重复性。", "The base score is 41.08. Both MiniMax M2.7 runs are near 49; GPT-5.6 xhigh reaches both 53.19 and 43.29, a 9.90-point span; Kimi K2.6, DeepSeek V4 Pro, and GPT-5.4 Pro also vary substantially. The target model changes both the search landscape and repeatability.")}</p><ResearchTable number={5} caption={tx("Qwen3-4B-Base 上的 17 次独立四小时运行，统计定义与 Table 4 相同。基础 checkpoint 的七任务均分为 41.08。该表应优先用来比较同一设置的重复范围，而不是仅按“最好分”排序。", "All 17 independent four-hour runs on Qwen3-4B-Base, using the same statistics as Table 4. The base checkpoint scores 41.08. The table should be read primarily as evidence about repeat variability within a setting, rather than as a ranking by Best alone.")}><RunSummaryTable rows={qwen3} language={language} /></ResearchTable>
        <h3>{tx("交互查看每一次运行", "Inspect every run interactively")}</h3><p>{tx("下面的视图读取与 Figure 5 相同的记录。切换目标模型并悬停蓝点，可以直接看到每次运行的分数，而不是只看平均值。", "The view below reads the same records as Figure 5. Switch the target model and hover over a blue dot to inspect individual runs rather than only their mean.")}</p><RunsExplorer language={language} />
        <div className="section-finding"><b>{tx("这些分数应该怎样读", "How these scores should be read")}</b><p>{tx("这些运行证明了多种 Agent 都能把流程跑通并找到涨分候选，也展示了各自可能达到的搜索上限。它们尚不能构成稳定排名：重复数量有限、每轮完成的候选数不同，而且最好分会放大采样运气。", "These runs show that several agents can execute the workflow and find improving candidates, while revealing their possible search ceilings. They do not yet form a stable ranking: repeats are limited, candidate counts differ, and best-of-run scores amplify sampling luck.")}</p></div>
      </section>

      <section id="traces"><h2>{tx("7. 搜索轨迹：不同 Agent 到底做了什么？", "7. Search trajectories: what did different agents actually do?")}</h2>
        <p>{tx("终点分数只回答“最后找到了什么”，trace 才能回答“它如何找到”。我们保存了 Agent 的命令、代码修改、每次评测、候选定义和 running-best 曲线，用来区分有状态的优化与独立随机抽样。", "Endpoint scores answer what was found; traces explain how. We preserve commands, code edits, evaluations, candidate definitions, and running-best curves to distinguish stateful optimization from independent random sampling.")}</p>
        <h3>{tx("从搜索代码到 checkpoint：逐步查看三条代表性轨迹", "From search code to checkpoints: three representative traces")}</h3>
        <p>{tx("这个交互视图不只画最终折线。它把一次运行拆成连续研究决策：Agent 当时写了什么搜索逻辑、用什么方式生成候选、看到怎样的分数，以及反馈为什么让它改变下一步。点击不同阶段可以沿着完整的优化路径阅读。", "This view goes beyond the final score curve. It breaks one run into consecutive research decisions: the search logic the agent wrote, how candidates were generated, what scores it observed, and why the feedback changed its next move. Select each stage to follow the optimization path.")}</p>
        <AgentTraceExplorer language={language} />
        <h3>{tx("四小时内，最好分数何时出现？", "When does improvement happen within four hours?")}</h3><div className="interactive-note">{tx("交互视图 · 可在时间/评测次数、汇总/单次运行之间切换；阴影表示重复运行范围。", "Interactive companion · switch between time/evaluation count and summary/individual runs; bands show the repeat range.")}</div><InteractiveTrajectory language={language} />
        <ResearchFigure number={6} src="/figures/agent_model_4h_trajectory.png" caption={tx("代表性 Agent 在四小时内的 running-best 轨迹。纵轴是在该时刻之前已经观察到的最好七任务均分。", "Representative running-best trajectories over four hours. The vertical axis is the best complete seven-task score observed up to each time.")} source="scripts/render_agent_4h_trajectory.py" interpretation={tx("发现｜高分出现的时间和改进次数差异很大。只比较最终点会丢掉样本效率：早期找到稳健方向并持续细化，与最后阶段碰到一次高分，是两种不同的研究行为。", "Finding｜The timing and number of improvements differ substantially. Endpoint-only comparison discards sample efficiency: finding a robust direction early and refining it is different from encountering one late high score.")} />
        <h3>{tx("trace 中观察到的策略差异", "Strategy differences observed in traces")}</h3><ul className="trace-list"><li><b>MiniMax M2.7.</b> {tx("较早使用正反方向评测和中心更新；在 Qwen3-4B 上的两次运行都接近 49，表现出相对稳定的有状态细化。", "It adopted antithetic evaluations and center updates early; both Qwen3-4B runs were near 49, showing relatively stable stateful refinement.")}</li><li><b>Kimi K2.6.</b> {tx("常先广泛探索，再围绕已有好点缩小尺度或组合方向。它能找到高分，但 Qwen3-4B 两次结果相差约 6.1 分。", "It often searched broadly before shrinking scale or combining directions around an incumbent. It found strong candidates, but its two Qwen3-4B results differed by about 6.1 points.")}</li><li><b>GLM-5.1.</b> {tx("倾向于先发现单一有效方向，再做尺度搜索和少量组合。Qwen2.5-3B 的重复较集中，但最终上限不领先。", "It tended to identify one useful direction and then search scale or a small number of combinations. Qwen2.5-3B repeats were tight, but the ceiling was not leading.")}</li><li><b>GPT-5.5 / GPT-5.6.</b> {tx("更常使用任务子集筛选和方向组合。GPT-5.6 xhigh 在 Qwen3-4B 上同时产生全体最高点与接近基础模型的一次运行，显示较高上限但不稳定。", "They more often used task-subset screening and direction combinations. GPT-5.6 xhigh produced both the overall best Qwen3-4B point and a run near the base, indicating high upside but poor stability.")}</li><li><b>Claude on Cursor.</b> {tx("能够主动编写和修改搜索代码并获得提升，但当前终点没有表现出与通用 Agent 榜单一致的优势。", "It actively wrote and revised search code and obtained improvements, but current endpoints do not mirror its advantage on general agent leaderboards.")}</li></ul>
        <h3>{tx("候选在权重空间里如何移动？", "How do candidates move through weight space?")}</h3><div className="interactive-note">{tx("交互视图 · 在 PCA 与固定随机投影之间切换，并选择七任务均分或单项分数着色。坐标只由权重差计算。", "Interactive companion · switch between PCA and a fixed random projection, then color by joint or per-task score. Coordinates use weight differences only.")}</div><WeightSpaceExplorer language={language} />
        <ResearchFigure number={7} src="/figures/agent-search-directions.png" caption={tx("六个 Agent 在统一二维投影中的有效改进路径。灰点是所有完整评测候选，彩色箭头只连接刷新历史最好分数的 checkpoint，菱形是基础模型，星号是该次运行最好点。", "Effective improvement paths for six agents in one shared two-dimensional projection. Gray points are all fully evaluated candidates, colored arrows connect only new incumbents, diamonds mark the base, and stars mark run bests.")} source="scripts/render_blog_extended_figures.py" interpretation={tx("发现｜不同 Agent 的路径形态与 trace 中的代码相符：有的持续移动中心，有的围绕基础模型独立抽样，有的只产生少量有效更新。投影用于比较行为，不是完整高维权重距离的精确地图。", "Finding｜Path shapes agree with the trace code: some agents move the center, some sample independently around the base, and some produce only a few effective updates. The projection compares behavior; it is not an exact map of full high-dimensional distance.")} />
        <div className="section-finding"><b>{tx("trace 比排行榜多告诉了我们什么", "What traces reveal beyond a leaderboard")}</b><p>{tx("模型之间确实存在可观察的研究行为差异，但“行为更复杂”不会自动带来更高终点分数。稳定的比较需要固定评测次数下的 running-best 曲线、最好点邻域复验和策略重放，而不是只奖励一次极值。", "Observable research behaviors differ across models, but more complex behavior does not automatically yield a higher endpoint. Stable comparison needs running-best curves at matched evaluation counts, neighborhood confirmation of incumbents, and strategy replay rather than a single extreme.")}</p></div>
      </section>

      <section id="conclusion"><h2>{tx("8. PostTrainBench⁰ 揭示了什么？", "8. What does PostTrainBench⁰ reveal?")}</h2>
        <p>{tx("PostTrainBench⁰ 把模型理解、代码实现、实验设计和数小时连续决策放进了同一个可验证循环。Agent 修改真实权重、读取真实分数、维护候选历史，并留下一个能够在全新推理实例中重放的模型。前提实验确认基础模型附近存在更好的多任务 checkpoint；51 次四小时运行则表明，当前 Agent 能够实际组织并推进这样的研究过程。不同 trace 还呈现出可区分的搜索风格：独立随机探测、正反方向比较、围绕已有好点缩小尺度，以及任务子集筛选与方向组合。", "PostTrainBench⁰ places model understanding, code implementation, experimental design, and hours of consecutive decisions inside one verifiable loop. The agent edits real weights, reads real scores, maintains a candidate history, and leaves a model that can be replayed in a fresh inference instance. The premise study confirms that better multi-task checkpoints exist near the base model, while 51 four-hour runs show that current agents can organize and advance this research process in practice. Their traces also reveal distinguishable search styles: independent random probes, antithetic comparisons, scale refinement around an incumbent, and task-subset screening followed by direction composition.")}</p>
        <h3>{tx("改进通常经历两个阶段", "Improvement usually unfolds in two phases")}</h3>
        <p>{tx("运行早期，Agent 往往用较宽的尺度或正反成对方向判断局部空间里是否存在信号；一旦出现有效方向，较好的轨迹会开始复用当前最好点，缩小尺度、组合方向，或先用薄弱任务筛选候选。于是，一条完整 trace 同时展示了探索和利用，也展示了 Agent 是否会从一次评测中提取可复用的信息。", "Early in a run, agents usually probe broad scales or antithetic directions to learn whether the local space contains signal. Once a useful direction appears, stronger traces reuse the incumbent, refine its scale, compose directions, or screen candidates on weak tasks. A complete trace therefore shows both exploration and exploitation—and whether an agent extracts reusable information from an evaluation.")}</p>
        <h3>{tx("一次最高分同时记录了策略与路径", "A run maximum records both strategy and path")}</h3>
        <p>{tx("固定候选能够被确定性重放，但找到它的过程仍然受候选覆盖范围、完整评测次数、系统吞吐和采样路径影响。我们在 Qwen3-4B 上看到同一 Agent 设置相差近 10 分，也看到结构更复杂的搜索不一定超过更简单的 ES 更新。因而，最高分最适合用来展示一次研究过程到达了哪里；把 Agent 作为研究员来比较时，还需要同时阅读 running-best 曲线、评测次数、方向复用和重复运行的分布。", "A fixed candidate can be replayed deterministically, while its discovery still depends on candidate coverage, the number of complete evaluations, system throughput, and the sampled path. On Qwen3-4B, repeats of one agent setting differ by nearly ten points, and structurally elaborate searches do not always beat a simpler ES update. The maximum is therefore most informative as the endpoint of one research process. Comparing agents as researchers also requires the running-best curve, evaluation count, direction reuse, and the distribution across repeats.")}</p>
        <h3>{tx("为什么公开这个实验", "Why we are releasing the experiment")}</h3>
        <p>{tx("后训练研究通常要求 Agent 同时处理数据、训练栈和大规模 GPU 作业。PostTrainBench⁰ 去掉显式梯度训练，把研究循环压缩为“提出权重修改—获得多任务分数—根据反馈继续实验”。这个较轻的 AI-for-AI 环境已经足以产生真实的模型改进，也让每次决策都能够被 trace 复查。公开代码、运行合约和交互轨迹，是为了让搜索算法、评测协议与 Agent 行为都成为可以共同研究的对象。", "Post-training research normally asks an agent to manage data, training stacks, and large GPU jobs at once. PostTrainBench⁰ removes explicit gradient training and compresses the research loop into proposing a weight edit, receiving multi-task scores, and experimenting again from feedback. This lighter AI-for-AI environment is already sufficient to produce real model improvements while leaving every decision inspectable in a trace. We release the code, runtime contract, and interactive trajectories so that search algorithms, evaluation protocols, and agent behavior can be studied together.")}</p>
        <p className="closing">{tx("我们发布 PostTrainBench⁰、实验 trace 和分析，希望更多研究者能够直接看到这个循环如何工作，复查其中的收益与波动，并提出更好的无梯度搜索算法和评测协议。它提供了一条成本较低、结果可重放的 AI-for-AI 实验路径，也让 Agent 如何通过真实实验改进模型成为一个可以共同推进的问题。", "We release PostTrainBench⁰, its experiment traces, and this analysis so that others can see the loop in action, inspect both its gains and its variation, and develop better gradient-free search algorithms and evaluation protocols. It offers a lower-cost, replayable path for AI-for-AI experimentation and makes agent-driven model improvement a concrete problem that the community can advance together.")}</p>
      </section>

      <section id="references"><h2>{tx("参考文献", "References")}</h2><ol className="references">
        <li id="ref-1"><b>Rank, B., Bhatnagar, H., Prabhu, A., Eisenberg, S., Nguyen, K., Bethge, M., &amp; Andriushchenko, M.</b> (2026). <cite>PostTrainBench: Can LLM Agents Automate LLM Post-Training?</cite> arXiv:2603.08640v2. <a href="https://doi.org/10.48550/arXiv.2603.08640">DOI</a> · <a href="https://posttrainbench.com/">Project website</a>.</li>
        <li id="ref-2"><b>Gan, Y., &amp; Isola, P.</b> (2026). <cite>Neural Thickets: Diverse Task Experts Are Dense Around Pretrained Weights.</cite> arXiv:2603.12228v1. <a href="https://doi.org/10.48550/arXiv.2603.12228">DOI</a> · <a href="https://thickets.mit.edu/">Project website</a>.</li>
        <li id="ref-3"><b>Qiu, X., Gan, Y., Hayes, C. F., Liang, Q., Xu, Y., Dailey, R., Meyerson, E., Hodjat, B., &amp; Miikkulainen, R.</b> (2026). <cite>Evolution Strategies at Scale: LLM Fine-Tuning Beyond Reinforcement Learning.</cite> ICML 2026; arXiv:2509.24372v3. <a href="https://doi.org/10.48550/arXiv.2509.24372">DOI</a> · <a href="https://github.com/VsonicV/es-at-scale">Code</a>.</li>
        <li id="ref-4"><b>Weng, L.</b> (2026). <cite>Harness Engineering for Self-Improvement.</cite> Lil&apos;Log, July 4, 2026. <a href="https://lilianweng.github.io/posts/2026-07-04-harness/">Article</a>.</li>
        <li id="ref-5"><b>Meng, F., Du, L., Chen, Q., Zhao, Z., Lu, H., Hu, M., &amp; Shieh, M. Q.</b> (2026). <cite>RSIBench-Data: Benchmarking Data-Centric Research for Recursive Self-Improvement.</cite> arXiv:2607.25886v1. <a href="https://doi.org/10.48550/arXiv.2607.25886">DOI</a> · <a href="https://github.com/evolvent-ai/RSIBench-Data">Code</a>.</li>
      </ol><h3>{tx("如何引用本博客", "How to cite this blog")}</h3><p>{tx("如果你使用 PostTrainBench⁰，或讨论本文公开的实验与分析，请引用下面的研究博客。", "If you use PostTrainBench⁰ or discuss the experiments and analysis presented here, please cite this research blog.")}</p><pre className="citation">{`@misc{tan2026posttrainbench0,\n  title        = {{PostTrainBench}$^{0}$: Can LLM Agents Automate LLM\n                  Post-Training Without Gradients?},\n  author       = {Tan, Yuqiao},\n  year         = {2026},\n  howpublished = {Research blog},\n  url          = {https://trae1oung.github.io/posttrainbench0/}\n}`}</pre></section>
    </article>
    <footer className="site-footer"><Wordmark /><span>Research blog · 2026</span><a href="#top">{tx("返回顶部", "Back to top")} ↑</a></footer>
  </main>;
}
